### PR TITLE
Dact 417

### PR DESCRIPTION
**Pull request by rwalrondch**
Change to add firstName and lastName to the filing as that is what chips filing consumer is looking for, rather than name.

### CODE REVIEW

**Comment by PhilipGlover** [comment]
more of a question  - if it's a corporate director, does the company name come from `name`?  
If so, should this code set the relevant fields in the OfficerFiling, or is it simpler just to leave like this, and let the chips-filing-consumer extract what it requires?

**Comment by rwalrondch** [comment]
> more of a question - if it's a corporate director, does the company name come from `name`? If so, should this code set the relevant fields in the OfficerFiling, or is it simpler just to leave like this, and let the chips-filing-consumer extract what it requires?

good question,  i believe corporate is in name,  but what I am not sure is how chips-filing-consumer / CHIPS expects to receive it.  If its in name then i think we will need to make a change in chips filing consumer,  if in first name lastName, then we will need to split it out from name into those 2.
I will ask that question to Mike and Craig and Leslie.

**Review by hepsimo — APPROVED** [review]
Changes look good. firstname and lastname checked already in unit test of description property

**Review by clewis1 — APPROVED** [review]
Looks good

**Pull request merged**
