### PR TITLE
DACT-387 : add endpoint for retrieving TM01 check your answers details

### PR DESCRIPTION
**Pull request by jbestwickch**
https://companieshouse.atlassian.net/browse/DACT-387
add endpoint for retrieving TM01 check your answers details. Add associated unit tests

### CODE REVIEW

**Comment by PhilipGlover** [comment]
This may be a similar comment to what I raised for another PR a few weeks ago, but it seems strange to be calling the officer Filing API to do what is only used in the officer web.  Ought the officer API have code in it only used by the officer web?
The officer web could have a service to call the appointments API to get the officer details and secondly call the officer Filing API to get the filing and thus the Resigned date.

**Comment by rwalrondch** [comment]
> This may be a similar comment to what I raised for another PR a few weeks ago, but it seems strange to be calling the officer Filing API to do what is only used in the officer web. Ought the officer API have code in it only used by the officer web? The officer web could have a service to call the appointments API to get the officer details and secondly call the officer Filing API to get the filing and thus the Resigned date.

Sorry yes similar answer as well :)
When it is a simple call to one thing,  then. yes we can go web straight out,  but when there are multiple calls, data manipulation etc, we should go via the API.
In this case we have to use the api anyway as we need to get the date of removal to show on the screen and that only exists within the filing, so we have to use officer-filing-api to access the filing.

**Review by rwalrondch — APPROVED** [review]

**Comment by mikemoore24** [comment]
Calls to the API to handle multiple calls, particularly where code hit on that call is re-usable for the API, is appropriate for the web to use. This however, I think stretches that purpose beyond being practical. We've made and registered a brand new endpoint to do 2 standard calls with a check on one field on the return of the first. As you mention, the Web will call the API for the submission data anyway so we can dismiss one of those. There's no part of this call which is re-usable in the API and the extra call we're talking about should be a standard, couple of lines of code - using the SDK - to retrieve the public data. 

The naming of this method should highlight the coupling here of the API to Web specific implementation. If this were a method which the API could make use of, or which is handling load, dependency chains and/or extra business logic for the web - it would be named based on it's function, not the check your answers page on the web client. i.e. what is it doing? Not what page do I need it for.

I think we've actually made more work for ourselves here and crossed the borders of responsibility for the Web/API services. However, I think the Node SDK has never been updated to do a single appointment call, so that could be considered a similar amount of work. In this case though, that update is more useful going forward than an endpoint tied to a check your answers page.

The Node SDK should have been updated to include a single appointment call (seems it only does List at the moment?) https://github.com/companieshouse/api-sdk-node/blob/d4e9e0052660cb61641056ab90080f98b21245c9/src/services/company-officers/service.ts 
Web can call the public data, check the resignation date and then get the filing data.

Also, unless this was supposed to be of use for software filers, this would be a private endpoint.

**Comment by rwalrondch** [comment]
> Calls to the API to handle multiple calls, particularly where code hit on that call is re-usable for the API, is appropriate for the web to use. This however, I think stretches that purpose beyond being practical. We've made and registered a brand new endpoint to do 2 standard calls with a check on one field on the return of the first. As you mention, the Web will call the API for the submission data anyway so we can dismiss one of those. There's no part of this call which is re-usable in the API and the extra call we're talking about should be a standard, couple of lines of code - using the SDK - to retrieve the public data.
> 
> The naming of this method should highlight the coupling here of the API to Web specific implementation. If this were a method which the API could make use of, or which is handling load, dependency chains and/or extra business logic for the web - it would be named based on it's function, not the check your answers page on the web client. i.e. what is it doing? Not what page do I need it for.
> 
> I think we've actually made more work for ourselves here and crossed the borders of responsibility for the Web/API services. However, I think the Node SDK has never been updated to do a single appointment call, so that could be considered a similar amount of work. In this case though, that update is more useful going forward than an endpoint tied to a check your answers page.
> 
> The Node SDK should have been updated to include a single appointment call (seems it only does List at the moment?) https://github.com/companieshouse/api-sdk-node/blob/d4e9e0052660cb61641056ab90080f98b21245c9/src/services/company-officers/service.ts Web can call the public data, check the resignation date and then get the filing data.
> 
> Also, unless this was supposed to be of use for software filers, this would be a private endpoint.

Can we pass this as is for now and I have booked a meeting on Tuesday to discuss the design details. Then we can create a new Jira to handle the way forward that gets agreed. Otherwise this story will not get completed by the end of sprint.

**Review by PhilipGlover — APPROVED** [review]
Further to comments above and discussion about redesigning this later, will approve now.
Yesterday I did run the code and call the new endpoint, which did successfully return the data as expected.

**Pull request merged**
