### PR TITLE
Update to nationality error tests

### PR DESCRIPTION
**Pull request by leighmcclurg**
https://companieshouse.atlassian.net/browse/DACT-914

Using updated api-enumerations in tests

### CODE REVIEW

**Review by rwalrondch — APPROVED** [review]

**Comment by mdesaikns** [comment]
I might be wrong but it looks like the change set does not contain the new version of api-enumerations?

**Review by clewis1 — DISMISSED** [review]

**Comment by clewis1** [comment]
Please don't merge until mdesaikns query is addressed.

**Comment by leighmcclurg** [comment]
> I might be wrong but it looks like the change set does not contain the new version of api-enumerations?

new version of api-enumerations added

**Review by clewis1 — APPROVED** [review]
api-enumerations added. Looks good.

**Pull request merged**
