### PR TITLE
DACT-790 removing middlenames as it breaks chips.

### PR DESCRIPTION
**Pull request by rwalrondch**

### CODE REVIEW

**Review by PhilipGlover — COMMENTED** [review]
Does the middle name need to be concatenated into the first name?  I'm not sure of this, but would CHIPS be able to split up names in this element?

**Review by hepsimo — DISMISSED** [review]
Changes look OK

**Comment by rwalrondch** [comment]
> ~Does the middle name need to be concatenated into the first name? I'm not sure of this, but would CHIPS be able to split up names in this element?~
> 
> .. Thinking about this further, I'm thinking that CHIPS should be able to handle middle names - this example in the CHIPS repo - https://github.com/companieshouse/chips/blob/develop/server/resource/EF%20per-form%20schemas/schemas%20and%20sample%20docs/ap01.1.xml - does show a ` <middlenames>` element. I haven't looked into this, but is the problem that the `chips-filing-consumer` isn't mapping this to the expected element for CHIPS??

Putting middlenames back in and extending its usage in the filing,  so it can be picked up in Chips filing consumer.

**Review by hepsimo — APPROVED** [review]
Changes look good

**Pull request merged**
